#!/usr/bin/env perl
# ftp_gui_build.pl --
#
# UI generated by GUI Builder Build 146 on 2016-09-11 18:31:45 from:
#    /home/harshil/osdl/perl/ftp_gui_build.ui
# This file is auto-generated.  Only the code within
#    '# BEGIN USER CODE'
#    '# END USER CODE'
# and code inside the callback subroutines will be round-tripped.
# The subroutine name 'ui' is reserved.
#

# Declare the package for this dialog
package ftp_gui_build;

# Locate this script so we can load the ui module
use FindBin qw($RealBin); use lib $RealBin; use ftp_gui_build_ui;

# BEGIN USER CODE

# END USER CODE

# BEGIN CALLBACK CODE
# ONLY EDIT CODE WITHIN THE SUB COMMANDS.

# connect_btn_command --
#
# Callback to handle $connect_btn widget option -command
#
# ARGS:
#    <NONE>
#
sub connect_btn_command {}

# cwd_btn_command --
#
# Callback to handle $cwd_btn widget option -command
#
# ARGS:
#    <NONE>
#
sub cwd_btn_command {}

# download_btn_command --
#
# Callback to handle $download_btn widget option -command
#
# ARGS:
#    <NONE>
#
sub download_btn_command {}

# file_value_invalidcommand --
#
# Callback to handle $file_value widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
sub file_value_invalidcommand {}

# file_value_validatecommand --
#
# Callback to handle $file_value widget option -validatecommand
#
# ARGS:
#    <NONE>
#
sub file_value_validatecommand {}

# file_value_xscrollcommand --
#
# Callback to handle $file_value widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
sub file_value_xscrollcommand {}

# files_list_text_xscrollcommand --
#
# Callback to handle $files_list_text widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
sub files_list_text_xscrollcommand {}

# files_list_text_yscrollcommand --
#
# Callback to handle $files_list_text widget option -yscrollcommand
#
# ARGS:
#    <NONE>
#
sub files_list_text_yscrollcommand {}

# host_value_invalidcommand --
#
# Callback to handle $host_value widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
sub host_value_invalidcommand {}

# host_value_validatecommand --
#
# Callback to handle $host_value widget option -validatecommand
#
# ARGS:
#    <NONE>
#
sub host_value_validatecommand {}

# host_value_xscrollcommand --
#
# Callback to handle $host_value widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
sub host_value_xscrollcommand {}

# log_text_xscrollcommand --
#
# Callback to handle $log_text widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
sub log_text_xscrollcommand {}

# log_text_yscrollcommand --
#
# Callback to handle $log_text widget option -yscrollcommand
#
# ARGS:
#    <NONE>
#
sub log_text_yscrollcommand {}

# pass_value_invalidcommand --
#
# Callback to handle $pass_value widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
sub pass_value_invalidcommand {}

# pass_value_validatecommand --
#
# Callback to handle $pass_value widget option -validatecommand
#
# ARGS:
#    <NONE>
#
sub pass_value_validatecommand {}

# pass_value_xscrollcommand --
#
# Callback to handle $pass_value widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
sub pass_value_xscrollcommand {}

# upload_btn_command --
#
# Callback to handle $upload_btn widget option -command
#
# ARGS:
#    <NONE>
#
sub upload_btn_command {}

# user_value_invalidcommand --
#
# Callback to handle $user_value widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
sub user_value_invalidcommand {}

# user_value_validatecommand --
#
# Callback to handle $user_value widget option -validatecommand
#
# ARGS:
#    <NONE>
#
sub user_value_validatecommand {}

# user_value_xscrollcommand --
#
# Callback to handle $user_value widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
sub user_value_xscrollcommand {}

# _text_2_xscrollcommand --
#
# Legacy command found in callback code. Add user comments inside body.
#
# ARGS:
#    <NONE>
#
sub _text_2_xscrollcommand {}

# _text_2_yscrollcommand --
#
# Legacy command found in callback code. Add user comments inside body.
#
# ARGS:
#    <NONE>
#
sub _text_2_yscrollcommand {}

# file_value_yscrollcommand --
#
# Legacy command found in callback code. Add user comments inside body.
#
# ARGS:
#    <NONE>
#
sub file_value_yscrollcommand {}

# END CALLBACK CODE

# Standalone Code Initialization - DO NOT EDIT
#
ftp_gui_build::userinit() if defined &ftp_gui_build::userinit;

our $top = MainWindow->new();
$top->title("ftp_gui_build");
ftp_gui_build::ui($top);

ftp_gui_build::run() if defined &ftp_gui_build::run;

Tk::MainLoop();

1;
