# ftp_gui_build_ui.pm --
#
# UI generated by GUI Builder Build 146 on 2016-09-11 18:31:45 from:
#    /home/harshil/osdl/perl/ftp_gui_build.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the package for this dialog
package ftp_gui_build;

use Tk;
use Tk::Menu;

# ftp_gui_build::ui --
#
# ARGS:
#   root     the parent window for this form
#
sub ftp_gui_build::ui {
    our($root) = @_;


    # Widget Initialization
    our($host_label) = $root->Label(
	-text => "Host:",
    );
    our($host_value) = $root->Entry(
	-background => "#ffffff",
	-width => 0,
    );
    our($user_label) = $root->Label(
	-text => "Username:",
    );
    our($user_value) = $root->Entry(
	-background => "#ffffff",
	-width => 0,
    );
    our($pass_label) = $root->Label(
	-text => "Password:",
    );
    our($pass_value) = $root->Entry(
	-background => "#ffffff",
	-show => "*",
	-width => 0,
    );
    our($connect_btn) = $root->Button(
	-background => "#cccccc",
	-text => "Connect",
    );
    our($cwd_btn) = $root->Button(
	-text => "Change directory",
    );
    our($download_btn) = $root->Button(
	-text => "Download",
    );
    our($upload_btn) = $root->Button(
	-text => "Upload",
    );
    our($log_text) = $root->Text(
	-background => "#ffffff",
	-height => 0,
	-takefocus => 1,
	-width => 0,
    );
    our($files_list_text) = $root->Text(
	-background => "#ffffff",
	-height => 0,
	-takefocus => 1,
	-width => 0,
    );
    our($fd_label) = $root->Label(
	-text => "Files and Directories",
    );
    our($file_value) = $root->Entry(
	-background => "#ffffff",
	-width => 0,
    );

    # widget commands

    $host_value->configure(
	-invalidcommand => \&host_value_invalidcommand
    );
    $host_value->configure(
	-validatecommand => \&host_value_validatecommand
    );
    $host_value->configure(
	-xscrollcommand => \&host_value_xscrollcommand
    );
    $user_value->configure(
	-invalidcommand => \&user_value_invalidcommand
    );
    $user_value->configure(
	-validatecommand => \&user_value_validatecommand
    );
    $user_value->configure(
	-xscrollcommand => \&user_value_xscrollcommand
    );
    $pass_value->configure(
	-invalidcommand => \&pass_value_invalidcommand
    );
    $pass_value->configure(
	-validatecommand => \&pass_value_validatecommand
    );
    $pass_value->configure(
	-xscrollcommand => \&pass_value_xscrollcommand
    );
    $connect_btn->configure(
	-command => \&connect_btn_command
    );
    $cwd_btn->configure(
	-command => \&cwd_btn_command
    );
    $download_btn->configure(
	-command => \&download_btn_command
    );
    $upload_btn->configure(
	-command => \&upload_btn_command
    );
    $log_text->configure(
	-xscrollcommand => \&log_text_xscrollcommand
    );
    $log_text->configure(
	-yscrollcommand => \&log_text_yscrollcommand
    );
    $files_list_text->configure(
	-xscrollcommand => \&files_list_text_xscrollcommand
    );
    $files_list_text->configure(
	-yscrollcommand => \&files_list_text_yscrollcommand
    );
    $file_value->configure(
	-invalidcommand => \&file_value_invalidcommand
    );
    $file_value->configure(
	-validatecommand => \&file_value_validatecommand
    );
    $file_value->configure(
	-xscrollcommand => \&file_value_xscrollcommand
    );


    # Geometry Management
    $host_label->grid(
	-in     => $root,
	-column => 1,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $host_value->grid(
	-in     => $root,
	-column => 2,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "ew"
    );
    $user_label->grid(
	-in     => $root,
	-column => 1,
	-row    => 2,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $user_value->grid(
	-in     => $root,
	-column => 2,
	-row    => 2,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "ew"
    );
    $pass_label->grid(
	-in     => $root,
	-column => 1,
	-row    => 3,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $pass_value->grid(
	-in     => $root,
	-column => 2,
	-row    => 3,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "ew"
    );
    $connect_btn->grid(
	-in     => $root,
	-column => 2,
	-row    => 4,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $cwd_btn->grid(
	-in     => $root,
	-column => 2,
	-row    => 6,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $download_btn->grid(
	-in     => $root,
	-column => 2,
	-row    => 8,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $upload_btn->grid(
	-in     => $root,
	-column => 2,
	-row    => 7,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $log_text->grid(
	-in     => $root,
	-column => 3,
	-row    => 1,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 3,
	-sticky => "news"
    );
    $files_list_text->grid(
	-in     => $root,
	-column => 3,
	-row    => 5,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 4,
	-sticky => "news"
    );
    $fd_label->grid(
	-in     => $root,
	-column => 3,
	-row    => 4,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $file_value->grid(
	-in     => $root,
	-column => 2,
	-row    => 5,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "ew"
    );


    # Resize Behavior
    $root->gridRowconfigure(1, -weight => 0, -minsize => 62, -pad => 0);
    $root->gridRowconfigure(2, -weight => 0, -minsize => 77, -pad => 0);
    $root->gridRowconfigure(3, -weight => 0, -minsize => 64, -pad => 0);
    $root->gridRowconfigure(4, -weight => 0, -minsize => 2, -pad => 0);
    $root->gridRowconfigure(5, -weight => 0, -minsize => 15, -pad => 0);
    $root->gridRowconfigure(6, -weight => 0, -minsize => 53, -pad => 0);
    $root->gridRowconfigure(7, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridRowconfigure(8, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(1, -weight => 0, -minsize => 54, -pad => 0);
    $root->gridColumnconfigure(2, -weight => 0, -minsize => 190, -pad => 0);
    $root->gridColumnconfigure(3, -weight => 0, -minsize => 612, -pad => 0);
}

1;
